version: 0.2

phases:
  pre_build:
    commands:
      - aws --version
      - echo $S3_BUCKET_NAME
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync build/ $S3_BUCKET_NAME
      - aws cloudfront create-invalidation --distribution-id=E1T48ODXMIKJ5P --paths /
      - echo 'DONE'