version: 0.2

phases:
  pre_build:
    commands:
      - aws --version
      - echo $S3_BUCKET_NAME
      - npm install
  build:
    commands:
      - npm run build
      - aws s3 sync build/ s3://$S3_BUCKET_NAME